[package]
name = "nexora"
version = "0.1.0"
description = "Tier-1 AI-Native Coding Assistant & Multi-Agent Desktop Orchestrator"
authors = ["Gautam <gautamcoder235>"]
license = "MIT"
repository = "https://github.com/gautamcoder235/Nexora"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "nexora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable", "test"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
portable-pty = "0.8"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.38.4"
rusqlite = { version = "0.31.0", features = ["bundled"] }
globset = "0.4.18"
wait-timeout = "0.2.1"
lazy_static = "1.5.0"
chrono = { version = "0.4.45", features = ["serde"] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
notify = { version = "7", default-features = false, features = ["macos_kqueue"] }
windows-sys = { version = "0.61.2", features = ["Win32_System_Console", "Win32_UI_WindowsAndMessaging"] }
nexora-core = { path = "../core" }
futures = "0.3.32"
blake3 = "1.5.4"

[features]
devtools = []
